// ===== CONFERENCE DATA =====
console.log('script.js is loading...');
const SHEET_URL = 'https://docs.google.com/spreadsheets/d/1AIGQPyms-ZimnswyB4e_3VwF72ZQ-C1n2UQBrxb8nfA/export?format=csv';

const scheduleData = {
    "Dec 12": {
        "Kalidas Auditorium": [
            { time: "09:15-09:20", title: "LIGHTING THE LAMP", type: "keynote" },
            { time: "09:20-09:30", title: "WELCOME ADDRESS BY ORGANIZING SECRETARY", type: "keynote" },
            { time: "09:30-09:45", title: "ADDRESS BY DIRECTOR, IIT KHARAGPUR", type: "keynote" },
            { time: "09:45-09:55", title: "ADDRESS BY DEAN CEP", type: "keynote" },
            { time: "09:55-10:00", title: "ADDRESS BY HEAD, OENA", type: "keynote" },
            { time: "10:00-10:05", title: "VOTE OF THANKS", type: "keynote" },
            { time: "10:05-10:35", title: "KEYNOTE ADDRESS: Prof. Balaji Ramakrishnan", type: "keynote" },
            { time: "10:35-10:50", title: "TEA BREAK", type: "break" },
            { time: "10:50-11:20", title: "KEYNOTE ADDRESS: Prof. Mike Meylan", type: "keynote" },
            { time: "11:20-11:50", title: "INVITED TALK: Prof. Sriram Venkatachalam", type: "invited" },
            { time: "11:50-12:20", title: "INVITED TALK: Prof. Justin Leontini", type: "invited" },
            { time: "12:20-12:35", title: "Shallow Water Marine Operations", id: "2" },
            { time: "12:35-12:50", title: "Hydrodynamic Response of a Semicircular Front-Face Pile Supported Breakwater", id: "10" },
            { time: "12:50-13:05", title: "Deflection of a floating ice sheet under a moving load: influence of uniform current and elastic bottom", id: "16" },
            { time: "13:05-14:00", title: "LUNCH BREAK", type: "break" },
            { time: "14:00-14:30", title: "KEYNOTE ADDRESS: Shri. Sumithran Sampath", type: "keynote" },
            { time: "14:30-15:00", title: "INVITED TALK: Prof. Abdus Samad", type: "invited" },
            { time: "15:00-15:30", title: "INVITED TALK: Dr. V Bharatwaja Srinivasan Ayyangar", type: "invited" },
            { time: "15:30-15:45", title: "Interaction of Water Waves by Multiple Porous Plates with Variable Porosity Over an Undulated Bottom", id: "20" },
            { time: "15:45-16:00", title: "Flow-Feeder Barge (FFB): An Integrated Solar-Powered Communication Superstructure for Smart Cage Aquaculture", id: "25" },
            { time: "16:00-16:15", title: "Fully nonlinear modelling of sloshing mode gap resonance between twin fixed barges in presence of uniform and shear current", id: "30" },
            { time: "16:15-16:30", title: "TEA BREAK", type: "break" },
            { time: "16:30-17:00", title: "DEPARTMENT PRESENTATION", type: "keynote" },
            { time: "17:00-17:15", title: "Hydrodynamic Performance of a Surface-Piercing Porous Structures with Hidden Chamber", id: "33" },
            { time: "17:15-17:30", title: "Shoreline Change Assessment Studies along Yarada Appikonda Coast, Andhra Pradesh", id: "35" },
            { time: "17:30-17:45", title: "Scattering of Surface Gravity Waves by an Array of Vertical Porous Structures Placed on Confined Porous Seabed", id: "34" },
            { time: "17:45-18:00", title: "Study on the spatial evolution of waves generated by steady wind forcing", id: "49" },
            { time: "19:00", title: "GRAND DINNER", type: "keynote" }
        ],
        "Gargi Auditorium": [
            { time: "11:20-11:50", title: "INVITED TALK: Dr Subhendu Maity", type: "invited" },
            { time: "12:20-12:35", title: "Arbitration Layer for Decision Making in Autonomous Underwater Robots", id: "3" },
            { time: "12:35-12:50", title: "Wave power generation and wave load analysis by a submerged piezoelectric plate in the presence of porous breakwater", id: "26" },
            { time: "12:50-13:05", title: "A Framework for assessing Underwater Radiated Noise from Shipping", id: "28" },
            { time: "14:30-15:00", title: "INVITED TALK: Dr Anindya Bhar", type: "invited" },
            { time: "15:00-15:30", title: "INVITED TALK: Prof. Abhijit Chaudhuri", type: "invited" },
            { time: "15:30-15:45", title: "Comparative Structural Analysis of Mild Steel and Duplex Stainless Steel for a 24.2-Meter Marine Pontoon", id: "41" },
            { time: "15:45-16:00", title: "Conceptual Development of Pin Piles for the Installation of Offshore Wind HVDC Substation Platform", id: "13" },
            { time: "16:00-16:15", title: "Fatigue Analysis for Installation of Subsea Pipelines in Shallow Waters", id: "29" },
            { time: "17:00-17:15", title: "Bio Inspired Propulsion_ Pulsatile Technology", id: "32" },
            { time: "17:15-17:30", title: "Physics-Informed Neural Networks (PINNs) Based Structural Health Monitoring for Floating Naval Docks", id: "37" },
            { time: "17:30-17:45", title: "Experimental investigation of freak wave interaction on a 5MW SPAR FOWT", id: "66" },
            { time: "17:45-18:00", title: "Numerical simulation of ship motions in regular waves in damaged condition", id: "46" }
        ],
        "Maitree Auditorium": [
            { time: "11:20-11:50", title: "INVITED TALK: Dr. Ritwik Ghoshal", type: "invited" },
            { time: "12:20-12:35", title: "Behaviour of a re-entrant auxetic core sandwich plate structure subject to an underwater explosion", id: "7" },
            { time: "12:35-12:50", title: "Parametric Investigation of Free Vibration Behavior in Functionally Graded Material Plates using HSDT", id: "8" },
            { time: "12:50-13:05", title: "Integrity Assessment and Life Extension of Ageing Offshore Structures", id: "17" },
            { time: "15:30-15:45", title: "Hatch Top Solar on a Bulk Carrier", id: "22" },
            { time: "15:45-16:00", title: "CFD-Based Performance Study of Buoyancy Modules Integration for Enhanced Cargo-Carrying Capacity in Shallow Waters", id: "73" },
            { time: "17:00-17:15", title: "Numerical study on bubble dynamics and safety implications in vertical and horizontal marine cryogenic tanks", id: "27" },
            { time: "17:15-17:30", title: "Numerical Investigation of Bubble-Induced Thermal Destratification in Marine and Offshore Cryogenic Storage Tanks", id: "40" },
            { time: "17:30-17:45", title: "VOF-Based Analysis of Bubble Formation and Free-Surface Deformation for Marine Aeration and Cryogenic Storage Systems", id: "43" },
            { time: "17:45-18:00", title: "Integrated Feasibility study and structural stability Assessment of an LNG-Powered Inland Cargo Carrier Operating in National Waterway-1", id: "69" }
        ]
    },
    "Dec 13": {
        "Kalidas Auditorium": [
            { time: "09:00-09:30", title: "KEYNOTE ADDRESS: Prof. Richard Manasseh", type: "keynote" },
            { time: "09:30-10:00", title: "KEYNOTE ADDRESS: Prof. Subhamoy Bhattacharya", type: "keynote" },
            { time: "10:00-10:15", title: "TEA BREAK", type: "break" },
            { time: "10:15-10:45", title: "INVITED TALK: Prof. Pankaj Biswas", type: "invited" },
            { time: "10:45-11:15", title: "INVITED TALK: Prof. Manasa Ranjan Behera", type: "invited" },
            { time: "11:15-11:30", title: "Prediction of ENS at weld root and toe of load carrying cruciform joints using ML", id: "44" },
            { time: "11:30-11:45", title: "Numerical model development and design of a hydraulic PTO for desalination of seawater using point absorber wave energy convertor", id: "47" },
            { time: "11:45-12:00", title: "Impact of Wave Directionality and Inter-Device Spacing on the Performance of Wave Energy Converter Arrays", id: "48" },
            { time: "12:00-12:15", title: "Integration of sinusoidal seabed and wave-absorbing seawall for mitigating harbour resonance", id: "58" },
            { time: "12:15-12:30", title: "Numerical Analysis of a Spar OTEC Platform Integrated with a Cold-Water Pipe", id: "64" },
            { time: "12:30-12:45", title: "Design Framework for River Cruise Vessel in India: A Study of Safety Features, Statutory Requirment and Global Best Practices", id: "70" },
            { time: "12:45-13:00", title: "Effect of CFD-Based Roll Damping on Ship Motion Response", id: "75" },
            { time: "13:00-14:00", title: "LUNCH BREAK", type: "break" },
            { time: "14:00-14:30", title: "KEYNOTE ADDRESS: Dr Tanmay Sarkar", type: "keynote" },
            { time: "14:30-15:00", title: "KEYNOTE ADDRESS: Prof. Hrishikesh Venkataraman", type: "keynote" },
            { time: "15:00-15:15", title: "Numerical Study of Contaminant Transportation by Advection and Diffusion", id: "80" },
            { time: "15:15-15:30", title: "Protection measures for the west coast of Tamilnadu", id: "81" },
            { time: "15:30-15:45", title: "Hydrodynamic Response of a Forced Porous Floating Flexible Plate under Oblique Wave Impact", id: "82" },
            { time: "16:30-17:00", title: "VALEDICTORY", type: "keynote" },
            { time: "17:00", title: "HIGH TEA", type: "break" }
        ],
        "Maitree Auditorium": [
            { time: "11:15-11:30", title: "Numerical Investigation of Flow Over a Flat Plate with Surface Hump: Effects on Boundary Layer Behavior", id: "52" },
            { time: "11:30-11:45", title: "Numerical Investigation of Flow Over a Flat Plate with Surface Hump: Effects on Boundary Layer Behavior", id: "52" },
            { time: "11:45-12:00", title: "Design requirement of mooring line stiffness through direct time-domain numerical simulation", id: "60" },
            { time: "12:00-12:15", title: "Parametric Investigation of the Efeect of Hybrid Drag Reduction System on a medium froude number displacement vessel", id: "63" },
            { time: "12:15-12:30", title: "Numerical Investigation and Validation of Hydrodynamic Performance and Cavitation Characteristics of the E779A Propeller", id: "79" },
            { time: "12:30-12:45", title: "Thrust Division and Efficiency of Co-rotating Ship propellers", id: "31" },
            { time: "12:45-13:00", title: "Impact of Water Scatter Diagram Choice on Second Generation Intact Stability Assessments", id: "76" },
            { time: "15:00-15:15", title: "Comparative Analysis of Propulsion System Layouts of a Catamaran Inland Passenger Ferry", id: "83" },
            { time: "15:15-15:30", title: "Numerical Validation of Hull Resistance considering Surface roughness Effects", id: "85" },
            { time: "15:30-15:45", title: "An efficient method for analysing the effects of wind propulsion on ship performance and seakeeping", id: "86" }
        ],
        "Gargi Auditorium": [
            { time: "11:15-11:30", title: "Vibroacoustic transmission analysis of complex structure within underwater layered media", id: "38" },
            { time: "11:30-11:45", title: "Development of General Guideline for Riverine floating HDPE Jetties Encapsulated by Steel Frame", id: "59" },
            { time: "11:45-12:00", title: "Evaluation of Container stowage and Securing Systems", id: "61" },
            { time: "12:00-12:15", title: "On Leveraging AI for Term Structure Understanding in Maritime Asset-Backed Deals", id: "65" },
            { time: "12:15-12:30", title: "AI-assisted Classification of Coating Conditions on Ship Plated Structures", id: "68" },
            { time: "12:30-12:45", title: "ANN-based prediction of VLE of N₂-CO₂ system for cryogenic carbon capture from ships", id: "12" },
            { time: "12:45-13:00", title: "Control Strategy for Cranes and Sensitivity to Delay", id: "45" },
            { time: "15:00-15:15", title: "Numerical Study on Nonlinear Structural Response of K Joints in Jacket-Type Offshore Wind Turbine Structures", id: "88" },
            { time: "15:15-15:30", title: "Marine Engine Crankshaft Strength and Fatigue Assessment Based on FE Analysis", id: "84" },
            { time: "15:30-15:45", title: "Design and Development of a Hybrid Finite Element Analysis Based Model Incorporating Temperature Dependent Material Properties for Impact Analysis of Blasts on Underwater Vehicles", id: "89" }
        ]
    }
};

let csvData = [];

// ===== CSV LOADING =====
async function loadCSV() {
    try {
        const response = await fetch(SHEET_URL);
        const text = await response.text();
        const rows = text.split('\n').map(row => row.split(','));
        csvData = rows.slice(1).map(row => ({
            id: row[0]?.trim(),
            name: row[1]?.trim(),
            location: row[2]?.trim(),
            time: row[3]?.trim(),
            date: row[4]?.trim()
        }));
    } catch (error) {
        console.error('Error loading CSV:', error);
    }
}

// ===== SCHEDULE RENDERING =====
function renderSchedule() {
    console.log('renderSchedule() called');
    const container = document.getElementById('scheduleContainer');
    console.log('scheduleContainer element:', container);

    if (!container) {
        console.error('ERROR: scheduleContainer element not found!');
        return;
    }

    let html = '';
    console.log('scheduleData:', scheduleData);

    for (const [day, venues] of Object.entries(scheduleData)) {
        console.log(`Processing day: ${day}`);
        html += `<div class="day-schedule">
            <div class="day-title">📆 ${day}th December, 2025</div>`;

        for (const [venue, sessions] of Object.entries(venues)) {
            console.log(`  Processing venue: ${venue}, sessions count: ${sessions.length}`);
            html += `<div class="venue-group">
                <div class="venue-title">📍 ${venue}</div>`;

            sessions.forEach(session => {
                const cardClass = session.type === 'keynote' ? 'session-card keynote' :
                    session.type === 'invited' ? 'session-card invited' :
                        session.type === 'break' ? 'session-card' : 'session-card';
                html += `<div class="${cardClass}">
                    <div class="session-time">⏰ ${session.time}</div>
                    <div class="session-title">${session.title}</div>
                    ${session.id ? `<div class="session-id">Abstract ID: ${session.id}</div>` : ''}
                </div>`;
            });

            html += `</div>`;
        }

        html += `</div>`;
    }

    console.log('Generated HTML length:', html.length);
    console.log('First 500 chars of HTML:', html.substring(0, 500));
    container.innerHTML = html;
    console.log('HTML set to container. Container innerHTML length:', container.innerHTML.length);
}


// ===== SEARCH FUNCTIONALITY =====
async function searchAbstract() {
    const searchInput = document.getElementById('searchInput').value.trim();
    const resultCard = document.getElementById('resultCard');
    const errorMessage = document.getElementById('errorMessage');
    const auditoriumResult = document.getElementById('auditoriumResult');

    resultCard.style.display = 'none';
    errorMessage.style.display = 'none';
    auditoriumResult.style.display = 'none';

    if (!searchInput) {
        errorMessage.textContent = 'Please enter an Abstract ID';
        errorMessage.style.display = 'block';
        return;
    }

    const result = csvData.find(item => item.id === searchInput);

    if (result) {
        resultCard.innerHTML = `
            <h3>📋 Abstract Details</h3>
            <div class="result-detail">
                <div class="result-label">Abstract ID:</div>
                <div class="result-value">${result.id}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Title:</div>
                <div class="result-value">${result.name}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Location:</div>
                <div class="result-value">${result.location}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Time:</div>
                <div class="result-value">${result.time}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Date:</div>
                <div class="result-value">${result.date}</div>
            </div>
        `;
        resultCard.style.display = 'block';
    } else {
        errorMessage.textContent = `No abstract found with ID: ${searchInput}`;
        errorMessage.style.display = 'block';
    }
}

// ===== AUDITORIUM FILTER =====
function showAuditoriumPrograms(auditoriumName) {
    const auditoriumResult = document.getElementById('auditoriumResult');
    const errorMessage = document.getElementById('errorMessage');
    const resultCard = document.getElementById('resultCard');

    // Hide other result displays
    resultCard.style.display = 'none';
    errorMessage.style.display = 'none';

    let programs = [];

    // Collect all programs for this auditorium from all days
    for (const [day, venues] of Object.entries(scheduleData)) {
        if (venues[auditoriumName]) {
            venues[auditoriumName].forEach(session => {
                programs.push({
                    day: day,
                    time: session.time,
                    title: session.title,
                    id: session.id || null,
                    type: session.type || null
                });
            });
        }
    }

    if (programs.length === 0) {
        errorMessage.textContent = `No programs found for ${auditoriumName}`;
        errorMessage.style.display = 'block';
        auditoriumResult.style.display = 'none';
        return;
    }

    // Build the result HTML
    let html = `<h3>🎭 Programs at ${auditoriumName}</h3>`;

    programs.forEach(program => {
        const dateText = program.day === "Dec 12" ? "December 12, 2025" : "December 13, 2025";
        html += `
            <div style="background: rgba(255,255,255,0.08); padding: 1.2rem; border-radius: 12px; margin-bottom: 1rem; border-left: 3px solid var(--color-accent-cyan);">
                <div class="result-detail">
                    <div class="result-label">Date:</div>
                    <div class="result-value">${dateText}</div>
                </div>
                <div class="result-detail">
                    <div class="result-label">Time:</div>
                    <div class="result-value">${program.time}</div>
                </div>
                <div class="result-detail">
                    <div class="result-label">Title:</div>
                    <div class="result-value">${program.title}</div>
                </div>
                ${program.id ? `
                <div class="result-detail">
                    <div class="result-label">Abstract ID:</div>
                    <div class="result-value">${program.id}</div>
                </div>
                ` : ''}
            </div>
        `;
    });

    auditoriumResult.innerHTML = html;
    auditoriumResult.style.display = 'block';
}

// ===== OCEAN WAVE ANIMATION =====
class OceanWaveSystem {
    constructor() {
        this.canvas = document.getElementById('particleCanvas');
        this.ctx = this.canvas.getContext('2d');
        this.waves = [];
        this.time = 0;

        this.init();
        this.animate();
        this.setupEventListeners();
    }

    init() {
        this.resizeCanvas();
        this.createWaves();
    }

    resizeCanvas() {
        this.canvas.width = window.innerWidth;
        this.canvas.height = window.innerHeight;
    }

    createWaves() {
        // Create multiple wave layers for depth
        this.waves = [
            {
                amplitude: 30,
                frequency: 0.01,
                speed: 0.02,
                yOffset: this.canvas.height * 0.3,
                color: 'rgba(0, 240, 255, 0.15)',
                lineWidth: 2
            },
            {
                amplitude: 40,
                frequency: 0.008,
                speed: 0.015,
                yOffset: this.canvas.height * 0.4,
                color: 'rgba(112, 0, 255, 0.12)',
                lineWidth: 2
            },
            {
                amplitude: 50,
                frequency: 0.012,
                speed: 0.025,
                yOffset: this.canvas.height * 0.5,
                color: 'rgba(0, 240, 255, 0.1)',
                lineWidth: 2
            },
            {
                amplitude: 35,
                frequency: 0.015,
                speed: 0.018,
                yOffset: this.canvas.height * 0.6,
                color: 'rgba(255, 0, 255, 0.08)',
                lineWidth: 2
            },
            {
                amplitude: 45,
                frequency: 0.009,
                speed: 0.022,
                yOffset: this.canvas.height * 0.7,
                color: 'rgba(0, 240, 255, 0.06)',
                lineWidth: 2
            }
        ];
    }

    drawWave(wave, time) {
        this.ctx.beginPath();
        this.ctx.moveTo(0, wave.yOffset);

        // Draw sine wave
        for (let x = 0; x <= this.canvas.width; x += 5) {
            const y = wave.yOffset +
                Math.sin(x * wave.frequency + time * wave.speed) * wave.amplitude +
                Math.sin(x * wave.frequency * 0.5 + time * wave.speed * 1.5) * (wave.amplitude * 0.5);
            this.ctx.lineTo(x, y);
        }

        // Fill below the wave
        this.ctx.lineTo(this.canvas.width, this.canvas.height);
        this.ctx.lineTo(0, this.canvas.height);
        this.ctx.closePath();

        // Gradient fill
        const gradient = this.ctx.createLinearGradient(0, wave.yOffset - wave.amplitude, 0, this.canvas.height);
        gradient.addColorStop(0, wave.color);
        gradient.addColorStop(1, 'rgba(0, 0, 0, 0)');

        this.ctx.fillStyle = gradient;
        this.ctx.fill();

        // Draw wave line
        this.ctx.beginPath();
        this.ctx.moveTo(0, wave.yOffset);
        for (let x = 0; x <= this.canvas.width; x += 5) {
            const y = wave.yOffset +
                Math.sin(x * wave.frequency + time * wave.speed) * wave.amplitude +
                Math.sin(x * wave.frequency * 0.5 + time * wave.speed * 1.5) * (wave.amplitude * 0.5);
            this.ctx.lineTo(x, y);
        }
        this.ctx.strokeStyle = wave.color.replace(/[\d.]+\)$/g, '0.3)');
        this.ctx.lineWidth = wave.lineWidth;
        this.ctx.stroke();
    }

    animate() {
        // Clear canvas
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);

        // Draw gradient background
        const gradient = this.ctx.createRadialGradient(
            this.canvas.width / 2, this.canvas.height / 2, 0,
            this.canvas.width / 2, this.canvas.height / 2, this.canvas.width / 2
        );
        gradient.addColorStop(0, '#0a0a0a');
        gradient.addColorStop(1, '#050505');
        this.ctx.fillStyle = gradient;
        this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);

        // Draw all waves
        this.waves.forEach(wave => {
            this.drawWave(wave, this.time);
        });

        // Add some floating bubbles/particles for extra ocean effect
        this.drawBubbles();

        this.time += 1;
        requestAnimationFrame(() => this.animate());
    }

    drawBubbles() {
        // Add subtle floating particles like underwater bubbles
        const bubbleCount = 20;
        for (let i = 0; i < bubbleCount; i++) {
            const x = (this.time * 0.5 + i * 50) % (this.canvas.width + 100);
            const baseY = this.canvas.height * 0.4 + (i * 30) % (this.canvas.height * 0.6);
            const y = baseY - (this.time * 0.3) % (this.canvas.height * 0.8);
            const size = 2 + Math.sin(this.time * 0.05 + i) * 1;
            const opacity = 0.1 + Math.sin(this.time * 0.03 + i) * 0.05;

            this.ctx.beginPath();
            this.ctx.arc(x, y, size, 0, Math.PI * 2);
            this.ctx.fillStyle = `rgba(0, 240, 255, ${opacity})`;
            this.ctx.fill();
        }
    }

    setupEventListeners() {
        window.addEventListener('resize', () => {
            this.resizeCanvas();
            this.createWaves();
        });
    }
}

// ===== SCROLL REVEAL ANIMATION =====
class ScrollReveal {
    constructor() {
        this.elements = document.querySelectorAll('.fade-in');
        this.init();
    }

    init() {
        this.observeElements();
    }

    observeElements() {
        const options = {
            threshold: 0.2,
            rootMargin: '0px 0px -100px 0px'
        };

        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('visible');
                }
            });
        }, options);

        this.elements.forEach(element => {
            observer.observe(element);
        });
    }
}

// ===== SMOOTH SCROLL =====
class SmoothScroll {
    constructor() {
        this.init();
    }

    init() {
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', (e) => {
                e.preventDefault();
                const target = document.querySelector(anchor.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                }
            });
        });
    }
}

// ===== NAVIGATION SCROLL EFFECT =====
class NavigationScroll {
    constructor() {
        this.nav = document.querySelector('.nav');
        this.init();
    }

    init() {
        window.addEventListener('scroll', () => {
            if (window.scrollY > 100) {
                this.nav.style.background = 'rgba(5, 5, 5, 0.95)';
                this.nav.style.boxShadow = '0 10px 30px rgba(0, 0, 0, 0.5)';
            } else {
                this.nav.style.background = 'rgba(5, 5, 5, 0.7)';
                this.nav.style.boxShadow = 'none';
            }
        });
    }
}

// ===== ENTER KEY SUPPORT =====
document.addEventListener('DOMContentLoaded', () => {
    const searchInput = document.getElementById('searchInput');
    if (searchInput) {
        searchInput.addEventListener('keypress', function (e) {
            if (e.key === 'Enter') {
                searchAbstract();
            }
        });
    }
});

// ===== INITIALIZE ALL =====
window.onload = async function () {
    try {
        console.log('Page loaded, initializing...');

        // Load conference data
        await loadCSV();
        console.log('CSV loaded');

        // Render schedule immediately
        renderSchedule();
        console.log('Schedule rendered');

        // Initialize visual effects
        new OceanWaveSystem();
        new SmoothScroll();
        new NavigationScroll();

        // Initialize scroll reveal AFTER a short delay to ensure schedule is visible
        setTimeout(() => {
            new ScrollReveal();
        }, 500);

        // Add loading animation
        document.body.style.opacity = '0';
        setTimeout(() => {
            document.body.style.transition = 'opacity 1s ease';
            document.body.style.opacity = '1';
        }, 100);

        console.log('Initialization complete');
    } catch (error) {
        console.error('ERROR in window.onload:', error);
    }
};
