// ===== CONFERENCE DATA =====
const SHEET_URL = 'https://docs.google.com/spreadsheets/d/1AIGQPyms-ZimnswyB4e_3VwF72ZQ-C1n2UQBrxb8nfA/export?format=csv';

const scheduleData = {
            "Dec 12": {
                "Kalidas Auditorium": [
                    {time: "09:15-09:20", title: "LIGHTING THE LAMP", type: "keynote"},
                    {time: "09:20-09:30", title: "WELCOME ADDRESS BY ORGANIZING SECRETARY", type: "keynote"},
                    {time: "09:30-09:45", title: "ADDRESS BY DIRECTOR, IIT KHARAGPUR", type: "keynote"},
                    {time: "09:45-09:55", title: "ADDRESS BY DEAN CEP", type: "keynote"},
                    {time: "09:55-10:00", title: "ADDRESS BY HEAD, OENA", type: "keynote"},
                    {time: "10:00-10:05", title: "VOTE OF THANKS", type: "keynote"},
                    {time: "10:05-10:35", title: "KEYNOTE ADDRESS: Prof. Balaji Ramakrishnan", type: "keynote"},
                    {time: "10:35-10:50", title: "TEA BREAK", type: "break"},
                    {time: "10:50-11:20", title: "KEYNOTE ADDRESS: Prof. Mike Meylan", type: "keynote"},
                    {time: "11:20-11:50", title: "INVITED TALK: Prof. Sriram Venkatachalam", type: "invited"},
                    {time: "11:50-12:20", title: "INVITED TALK: Prof. Justin Leontini", type: "invited"},
                    {time: "12:20-12:35", title: "Shallow Water Marine Operations", id: "2"},
                    {time: "12:35-12:50", title: "Hydrodynamic Response of a Semicircular Front-Face Pile Supported Breakwater", id: "10"},
                    {time: "12:50-13:05", title: "Deflection of a floating ice sheet under a moving load: influence of uniform current and elastic bottom", id: "16"},
                    {time: "13:05-14:00", title: "LUNCH BREAK", type: "break"},
                    {time: "14:00-14:30", title: "KEYNOTE ADDRESS: Shri. Sumithran Sampath", type: "keynote"},
                    {time: "14:30-15:00", title: "INVITED TALK: Prof. Abdus Samad", type: "invited"},
                    {time: "15:00-15:30", title: "INVITED TALK: Dr. V Bharatwaja Srinivasan Ayyangar", type: "invited"},
                    {time: "15:30-15:45", title: "Interaction of Water Waves by Multiple Porous Plates with Variable Porosity Over an Undulated Bottom", id: "20"},
                    {time: "15:45-16:00", title: "Flow-Feeder Barge (FFB): An Integrated Solar-Powered Communication Superstructure for Smart Cage Aquaculture", id: "25"},
                    {time: "16:00-16:15", title: "Fully nonlinear modelling of sloshing mode gap resonance between twin fixed barges in presence of uniform and shear current", id: "30"},
                    {time: "16:15-16:30", title: "TEA BREAK", type: "break"},
                    {time: "16:30-17:00", title: "DEPARTMENT PRESENTATION", type: "keynote"},
                    {time: "17:00-17:15", title: "Hydrodynamic Performance of a Surface-Piercing Porous Structures with Hidden Chamber", id: "33"},
                    {time: "17:15-17:30", title: "Shoreline Change Assessment Studies along Yarada Appikonda Coast, Andhra Pradesh", id: "35"},
                    {time: "17:30-17:45", title: "Scattering of Surface Gravity Waves by an Array of Vertical Porous Structures Placed on Confined Porous Seabed", id: "34"},
                    {time: "17:45-18:00", title: "Study on the spatial evolution of waves generated by steady wind forcing", id: "49"},
                    {time: "19:00", title: "GRAND DINNER", type: "keynote"}
                ],
                "Gargi Auditorium": [
                    {time: "11:20-11:50", title: "INVITED TALK: Dr Subhendu Maity", type: "invited"},
                    {time: "12:20-12:35", title: "Arbitration Layer for Decision Making in Autonomous Underwater Robots", id: "3"},
                    {time: "12:35-12:50", title: "Wave power generation and wave load analysis by a submerged piezoelectric plate in the presence of porous breakwater", id: "26"},
                    {time: "12:50-13:05", title: "A Framework for assessing Underwater Radiated Noise from Shipping", id: "28"},
                    {time: "14:30-15:00", title: "INVITED TALK: Dr Anindya Bhar", type: "invited"},
                    {time: "15:00-15:30", title: "INVITED TALK: Prof. Abhijit Chaudhuri", type: "invited"},
                    {time: "15:30-15:45", title: "Comparative Structural Analysis of Mild Steel and Duplex Stainless Steel for a 24.2-Meter Marine Pontoon", id: "41"},
                    {time: "15:45-16:00", title: "Conceptual Development of Pin Piles for the Installation of Offshore Wind HVDC Substation Platform", id: "13"},
                    {time: "16:00-16:15", title: "Fatigue Analysis for Installation of Subsea Pipelines in Shallow Waters", id: "29"},
                    {time: "17:00-17:15", title: "Bio Inspired Propulsion_ Pulsatile Technology", id: "32"},
                    {time: "17:15-17:30", title: "Physics-Informed Neural Networks (PINNs) Based Structural Health Monitoring for Floating Naval Docks", id: "37"},
                    {time: "17:30-17:45", title: "Experimental investigation of freak wave interaction on a 5MW SPAR FOWT", id: "66"},
                    {time: "17:45-18:00", title: "Numerical simulation of ship motions in regular waves in damaged condition", id: "46"}
                ],
                "Maitree Auditorium": [
                    {time: "12:20-12:35", title: "Behaviour of a re-entrant auxetic core sandwich plate structure subject to an underwater explosion", id: "7"},
                    {time: "12:35-12:50", title: "Parametric Investigation of Free Vibration Behavior in Functionally Graded Material Plates using HSDT", id: "8"},
                    {time: "12:50-13:05", title: "Integrity Assessment and Life Extension of Ageing Offshore Structures", id: "17"},
                    {time: "15:30-15:45", title: "Hatch Top Solar on a Bulk Carrier", id: "22"},
                    {time: "15:45-16:00", title: "CFD-Based Performance Study of Buoyancy Modules Integration for Enhanced Cargo-Carrying Capacity in Shallow Waters", id: "73"},
                    {time: "17:00-17:15", title: "Numerical study on bubble dynamics and safety implications in vertical and horizontal marine cryogenic tanks", id: "27"},
                    {time: "17:15-17:30", title: "Numerical Investigation of Bubble-Induced Thermal Destratification in Marine and Offshore Cryogenic Storage Tanks", id: "40"},
                    {time: "17:30-17:45", title: "VOF-Based Analysis of Bubble Formation and Free-Surface Deformation for Marine Aeration and Cryogenic Storage Systems", id: "43"},
                    {time: "17:45-18:00", title: "Integrated Feasibility study and structural stability Assessment of an LNG-Powered Inland Cargo Carrier Operating in National Waterway-1", id: "69"}
                ]
            },
            "Dec 13": {
                "Kalidas Auditorium": [
                    {time: "09:00-09:30", title: "KEYNOTE ADDRESS: Prof. Richard Manasseh", type: "keynote"},
                    {time: "09:30-10:00", title: "KEYNOTE ADDRESS: Prof. Subhamoy Bhattacharya", type: "keynote"},
                    {time: "10:00-10:15", title: "TEA BREAK", type: "break"},
                    {time: "10:15-10:45", title: "INVITED TALK: Prof. Pankaj Biswas", type: "invited"},
                    {time: "10:45-11:15", title: "INVITED TALK: Prof. Manasa Ranjan Behera", type: "invited"},
                    {time: "11:15-11:30", title: "Prediction of ENS at weld root and toe of load carrying cruciform joints using ML", id: "44"},
                    {time: "11:30-11:45", title: "Numerical model development and design of a hydraulic PTO for desalination of seawater using point absorber wave energy convertor", id: "47"},
                    {time: "11:45-12:00", title: "Impact of Wave Directionality and Inter-Device Spacing on the Performance of Wave Energy Converter Arrays", id: "48"},
                    {time: "12:00-12:15", title: "Integration of sinusoidal seabed and wave-absorbing seawall for mitigating harbour resonance", id: "58"},
                    {time: "12:15-12:30", title: "Numerical Analysis of a Spar OTEC Platform Integrated with a Cold-Water Pipe", id: "64"},
                    {time: "12:30-12:45", title: "Design Framework for River Cruise Vessel in India: A Study of Safety Features, Statutory Requirment and Global Best Practices", id: "70"},
                    {time: "12:45-13:00", title: "Effect of CFD-Based Roll Damping on Ship Motion Response", id: "75"},
                    {time: "13:00-14:00", title: "LUNCH BREAK", type: "break"},
                    {time: "14:00-14:30", title: "KEYNOTE ADDRESS: Dr Tanmay Sarkar", type: "keynote"},
                    {time: "14:30-15:00", title: "KEYNOTE ADDRESS: Prof. Hrishikesh Venkataraman", type: "keynote"},
                    {time: "15:00-15:15", title: "Numerical Study of Contaminant Transportation by Advection and Diffusion", id: "80"},
                    {time: "15:15-15:30", title: "Protection measures for the west coast of Tamilnadu", id: "81"},
                    {time: "15:30-15:45", title: "Hydrodynamic Response of a Forced Porous Floating Flexible Plate under Oblique Wave Impact", id: "82"},
                    {time: "16:30-17:00", title: "VALEDICTORY", type: "keynote"},
                    {time: "17:00", title: "HIGH TEA", type: "break"}
                ],
                "Maitree Auditorium": [
                    {time: "10:15-10:45", title: "INVITED TALK: Dr Harekrushna Behera", type: "invited"},
                    {time: "11:15-11:30", title: "Turning Performance Analysis of Multi-AUV formations: Hydrodynamic Effect of Configuration on Maneuvering Charactertics", id: "51"},
                    {time: "11:30-11:45", title: "Numerical Investigation of Flow Over a Flat Plate with Surface Hump: Effects on Boundary Layer Behavior", id: "52"},
                    {time: "11:45-12:00", title: "Design requirement of mooring line stiffness through direct time-domain numerical simulation", id: "60"},
                    {time: "12:00-12:15", title: "Parametric Investigation of the Efeect of Hybrid Drag Reduction System on a medium froude number displacement vessel", id: "63"},
                    {time: "12:15-12:30", title: "Numerical Investigation and Validation of Hydrodynamic Performance and Cavitation Characteristics of the E779A Propeller", id: "79"},
                    {time: "12:30-12:45", title: "Thrust Division and Efficiency of Co-rotating Ship propellers", id: "31"},
                    {time: "12:45-13:00", title: "Impact of Water Scatter Diagram Choice on Second Generation Intact Stability Assessments", id: "76"},
                    {time: "15:00-15:15", title: "Comparative Analysis of Propulsion System Layouts of a Catamaran Inland Passenger Ferry", id: "83"},
                    {time: "15:15-15:30", title: "Numerical Validation of Hull Resistance considering Surface roughness Effects", id: "85"},
                    {time: "15:30-15:45", title: "An efficient method for analysing the effects of wind propulsion on ship performance and seakeeping", id: "86"}
                ],
                "Gargi Auditorium": [
                    {time: "11:15-11:30", title: "Vibroacoustic transmission analysis of complex structure within underwater layered media", id: "38"},
                    {time: "11:30-11:45", title: "Development of General Guideline for Riverine floating HDPE Jetties Encapsulated by Steel Frame", id: "59"},
                    {time: "11:45-12:00", title: "Evaluation of Container stowage and Securing Systems", id: "61"},
                    {time: "12:00-12:15", title: "On Leveraging AI for Term Structure Understanding in Maritime Asset-Backed Deals", id: "65"},
                    {time: "12:15-12:30", title: "AI-assisted Classification of Coating Conditions on Ship Plated Structures", id: "68"},
                    {time: "12:30-12:45", title: "ANN-based prediction of VLE of N₂-CO₂ system for cryogenic carbon capture from ships", id: "12"},
                    {time: "12:45-13:00", title: "Control Strategy for Cranes and Sensitivity to Delay", id: "45"},
                    {time: "15:00-15:15", title: "Numerical Study on Nonlinear Structural Response of K Joints in Jacket-Type Offshore Wind Turbine Structures", id: "88"},
                    {time: "15:15-15:30", title: "Marine Engine Crankshaft Strength and Fatigue Assessment Based on FE Analysis", id: "84"},
                    {time: "15:30-15:45", title: "Design and Development of a Hybrid Finite Element Analysis Based Model Incorporating Temperature Dependent Material Properties for Impact Analysis of Blasts on Underwater Vehicles", id: "89"}
                ]
            }
        };

let csvData = [];

// ===== CSV LOADING =====
async function loadCSV() {
    try {
        const response = await fetch(SHEET_URL);
        const text = await response.text();
        const rows = text.split('\n').map(row => row.split(','));
        csvData = rows.slice(1).map(row => ({
            id: row[0]?.trim(),
            name: row[1]?.trim(),
            location: row[2]?.trim(),
            time: row[3]?.trim(),
            date: row[4]?.trim()
        }));
    } catch (error) {
        console.error('Error loading CSV:', error);
    }
}

// ===== SCHEDULE RENDERING =====
function renderSchedule() {
    const container = document.getElementById('scheduleContainer');
    let html = '';

    for (const [day, venues] of Object.entries(scheduleData)) {
        html += `<div class="day-schedule fade-in">
            <div class="day-title">📆 ${day}th December, 2025</div>`;

        for (const [venue, sessions] of Object.entries(venues)) {
            html += `<div class="venue-group">
                <div class="venue-title">📍 ${venue}</div>`;

            sessions.forEach(session => {
                const cardClass = session.type === 'keynote' ? 'session-card keynote' :
                    session.type === 'invited' ? 'session-card invited' :
                        session.type === 'break' ? 'session-card' : 'session-card';
                html += `<div class="${cardClass}">
                    <div class="session-time">⏰ ${session.time}</div>
                    <div class="session-title">${session.title}</div>
                    ${session.id ? `<div class="session-id">Abstract ID: ${session.id}</div>` : ''}
                </div>`;
            });

            html += `</div>`;
        }

        html += `</div>`;
    }

    container.innerHTML = html;
}

// ===== SEARCH FUNCTIONALITY =====
async function searchAbstract() {
    const searchInput = document.getElementById('searchInput').value.trim();
    const resultCard = document.getElementById('resultCard');
    const errorMessage = document.getElementById('errorMessage');
    const auditoriumResult = document.getElementById('auditoriumResult');

    resultCard.style.display = 'none';
    errorMessage.style.display = 'none';
    auditoriumResult.style.display = 'none';

    if (!searchInput) {
        errorMessage.textContent = 'Please enter an Abstract ID';
        errorMessage.style.display = 'block';
        return;
    }

    const result = csvData.find(item => item.id === searchInput);

    if (result) {
        resultCard.innerHTML = `
            <h3>📋 Abstract Details</h3>
            <div class="result-detail">
                <div class="result-label">Abstract ID:</div>
                <div class="result-value">${result.id}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Title:</div>
                <div class="result-value">${result.name}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Location:</div>
                <div class="result-value">${result.location}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Time:</div>
                <div class="result-value">${result.time}</div>
            </div>
            <div class="result-detail">
                <div class="result-label">Date:</div>
                <div class="result-value">${result.date}</div>
            </div>
        `;
        resultCard.style.display = 'block';
    } else {
        errorMessage.textContent = `No abstract found with ID: ${searchInput}`;
        errorMessage.style.display = 'block';
    }
}

// ===== AUDITORIUM FILTER =====
function showAuditoriumPrograms(auditoriumName) {
    const auditoriumResult = document.getElementById('auditoriumResult');
    const errorMessage = document.getElementById('errorMessage');
    const resultCard = document.getElementById('resultCard');

    // Hide other result displays
    resultCard.style.display = 'none';
    errorMessage.style.display = 'none';

    let programs = [];

    // Collect all programs for this auditorium from all days
    for (const [day, venues] of Object.entries(scheduleData)) {
        if (venues[auditoriumName]) {
            venues[auditoriumName].forEach(session => {
                programs.push({
                    day: day,
                    time: session.time,
                    title: session.title,
                    id: session.id || null,
                    type: session.type || null
                });
            });
        }
    }

    if (programs.length === 0) {
        errorMessage.textContent = `No programs found for ${auditoriumName}`;
        errorMessage.style.display = 'block';
        auditoriumResult.style.display = 'none';
        return;
    }

    // Build the result HTML
    let html = `<h3>🎭 Programs at ${auditoriumName}</h3>`;

    programs.forEach(program => {
        const dateText = program.day === "Dec 12" ? "December 12, 2025" : "December 13, 2025";
        html += `
            <div style="background: rgba(255,255,255,0.08); padding: 1.2rem; border-radius: 12px; margin-bottom: 1rem; border-left: 3px solid var(--color-accent-cyan);">
                <div class="result-detail">
                    <div class="result-label">Date:</div>
                    <div class="result-value">${dateText}</div>
                </div>
                <div class="result-detail">
                    <div class="result-label">Time:</div>
                    <div class="result-value">${program.time}</div>
                </div>
                <div class="result-detail">
                    <div class="result-label">Title:</div>
                    <div class="result-value">${program.title}</div>
                </div>
                ${program.id ? `
                <div class="result-detail">
                    <div class="result-label">Abstract ID:</div>
                    <div class="result-value">${program.id}</div>
                </div>
                ` : ''}
            </div>
        `;
    });

    auditoriumResult.innerHTML = html;
    auditoriumResult.style.display = 'block';
}

// ===== PARTICLE ANIMATION =====
class ParticleSystem {
    constructor() {
        this.canvas = document.getElementById('particleCanvas');
        this.ctx = this.canvas.getContext('2d');
        this.particles = [];
        this.particleCount = 150;
        this.connectionDistance = 150;
        this.mouse = { x: null, y: null, radius: 150 };

        this.init();
        this.animate();
        this.setupEventListeners();
    }

    init() {
        this.resizeCanvas();
        this.createParticles();
    }

    resizeCanvas() {
        this.canvas.width = window.innerWidth;
        this.canvas.height = window.innerHeight;
    }

    createParticles() {
        this.particles = [];
        for (let i = 0; i < this.particleCount; i++) {
            this.particles.push({
                x: Math.random() * this.canvas.width,
                y: Math.random() * this.canvas.height,
                vx: (Math.random() - 0.5) * 0.5,
                vy: (Math.random() - 0.5) * 0.5,
                size: Math.random() * 2 + 1
            });
        }
    }

    drawParticles() {
        this.particles.forEach(particle => {
            this.ctx.beginPath();
            this.ctx.arc(particle.x, particle.y, particle.size, 0, Math.PI * 2);
            this.ctx.fillStyle = 'rgba(0, 240, 255, 0.6)';
            this.ctx.fill();
        });
    }

    updateParticles() {
        this.particles.forEach(particle => {
            particle.x += particle.vx;
            particle.y += particle.vy;

            // Bounce off edges
            if (particle.x < 0 || particle.x > this.canvas.width) particle.vx *= -1;
            if (particle.y < 0 || particle.y > this.canvas.height) particle.vy *= -1;

            // Mouse interaction
            if (this.mouse.x !== null && this.mouse.y !== null) {
                const dx = this.mouse.x - particle.x;
                const dy = this.mouse.y - particle.y;
                const distance = Math.sqrt(dx * dx + dy * dy);

                if (distance < this.mouse.radius) {
                    const force = (this.mouse.radius - distance) / this.mouse.radius;
                    const angle = Math.atan2(dy, dx);
                    particle.vx -= Math.cos(angle) * force * 0.2;
                    particle.vy -= Math.sin(angle) * force * 0.2;
                }
            }

            // Damping
            particle.vx *= 0.99;
            particle.vy *= 0.99;
        });
    }

    drawConnections() {
        for (let i = 0; i < this.particles.length; i++) {
            for (let j = i + 1; j < this.particles.length; j++) {
                const dx = this.particles[i].x - this.particles[j].x;
                const dy = this.particles[i].y - this.particles[j].y;
                const distance = Math.sqrt(dx * dx + dy * dy);

                if (distance < this.connectionDistance) {
                    const opacity = (1 - distance / this.connectionDistance) * 0.3;
                    this.ctx.beginPath();
                    this.ctx.strokeStyle = `rgba(0, 240, 255, ${opacity})`;
                    this.ctx.lineWidth = 1;
                    this.ctx.moveTo(this.particles[i].x, this.particles[i].y);
                    this.ctx.lineTo(this.particles[j].x, this.particles[j].y);
                    this.ctx.stroke();
                }
            }
        }
    }

    animate() {
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);

        // Draw gradient background
        const gradient = this.ctx.createRadialGradient(
            this.canvas.width / 2, this.canvas.height / 2, 0,
            this.canvas.width / 2, this.canvas.height / 2, this.canvas.width / 2
        );
        gradient.addColorStop(0, '#0a0a0a');
        gradient.addColorStop(1, '#050505');
        this.ctx.fillStyle = gradient;
        this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);

        this.updateParticles();
        this.drawConnections();
        this.drawParticles();

        requestAnimationFrame(() => this.animate());
    }

    setupEventListeners() {
        window.addEventListener('resize', () => {
            this.resizeCanvas();
            this.createParticles();
        });

        window.addEventListener('mousemove', (e) => {
            this.mouse.x = e.x;
            this.mouse.y = e.y;
        });

        window.addEventListener('mouseleave', () => {
            this.mouse.x = null;
            this.mouse.y = null;
        });
    }
}

// ===== SCROLL REVEAL ANIMATION =====
class ScrollReveal {
    constructor() {
        this.elements = document.querySelectorAll('.fade-in');
        this.init();
    }

    init() {
        this.observeElements();
    }

    observeElements() {
        const options = {
            threshold: 0.2,
            rootMargin: '0px 0px -100px 0px'
        };

        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('visible');
                }
            });
        }, options);

        this.elements.forEach(element => {
            observer.observe(element);
        });
    }
}

// ===== SMOOTH SCROLL =====
class SmoothScroll {
    constructor() {
        this.init();
    }

    init() {
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {
            anchor.addEventListener('click', (e) => {
                e.preventDefault();
                const target = document.querySelector(anchor.getAttribute('href'));
                if (target) {
                    target.scrollIntoView({
                        behavior: 'smooth',
                        block: 'start'
                    });
                }
            });
        });
    }
}

// ===== NAVIGATION SCROLL EFFECT =====
class NavigationScroll {
    constructor() {
        this.nav = document.querySelector('.nav');
        this.init();
    }

    init() {
        window.addEventListener('scroll', () => {
            if (window.scrollY > 100) {
                this.nav.style.background = 'rgba(5, 5, 5, 0.95)';
                this.nav.style.boxShadow = '0 10px 30px rgba(0, 0, 0, 0.5)';
            } else {
                this.nav.style.background = 'rgba(5, 5, 5, 0.7)';
                this.nav.style.boxShadow = 'none';
            }
        });
    }
}

// ===== ENTER KEY SUPPORT =====
document.addEventListener('DOMContentLoaded', () => {
    const searchInput = document.getElementById('searchInput');
    if (searchInput) {
        searchInput.addEventListener('keypress', function (e) {
            if (e.key === 'Enter') {
                searchAbstract();
            }
        });
    }
});

// ===== INITIALIZE ALL =====
window.onload = async function () {
    // Load conference data
    await loadCSV();
    renderSchedule();

    // Initialize visual effects
    new ParticleSystem();
    new ScrollReveal();
    new SmoothScroll();
    new NavigationScroll();

    // Add loading animation
    document.body.style.opacity = '0';
    setTimeout(() => {
        document.body.style.transition = 'opacity 1s ease';
        document.body.style.opacity = '1';
    }, 100);
};

